# Generated by Django 4.2 on 2024-07-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopowner'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shopowner'),
        ),
    ]
