# Generated by Django 4.2 on 2024-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_staff_nid_no_userrole'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
