# Generated by Django 4.2 on 2024-07-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_delete_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopowner',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shopOwner', 'ShopOwner'), ('employee', 'Employee')], default='shopOwner', max_length=15),
        ),
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('shopOwner', 'ShopOwner'), ('employee', 'Employee')], default='employee', max_length=15),
        ),
    ]
