# Generated by Django 4.2 on 2024-07-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_shopowner_role_staff_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopowner',
            name='role',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
    ]
