# Generated by Django 5.0.2 on 2024-02-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_catagory_product_catagory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
