# Generated by Django 4.2 on 2024-03-19 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='product',
            name='qr_iamge',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_image'),
        ),
        migrations.DeleteModel(
            name='Catagory',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
    ]
