# Generated by Django 4.2 on 2024-03-19 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_category_remove_product_catagory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('tax_id', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='is_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_create_date',
        ),
        migrations.AddField(
            model_name='product',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.supplier'),
        ),
    ]
