# Generated by Django 4.2 on 2024-03-20 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
