# Generated by Django 4.2 on 2024-03-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_product_buy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='sell_price',
        ),
    ]
