# Generated by Django 4.2 on 2024-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventory_product_inventory_products'),
        ('product', '0015_remove_product_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='inventory_entries',
            field=models.ManyToManyField(related_name='related_products', to='inventory.inventory'),
        ),
    ]
