# Generated by Django 4.2 on 2024-03-21 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventory_product_inventory_products'),
        ('product', '0016_product_inventory_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='inventory_entries',
        ),
        migrations.AddField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_products', to='inventory.inventory'),
        ),
    ]
