# Generated by Django 4.2 on 2024-03-26 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventory_product_remove_inventory_subtotal_and_more'),
        ('product', '0017_remove_product_inventory_entries_product_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='inventory.inventory'),
        ),
    ]
