# Generated by Django 4.2 on 2024-03-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subtotal',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('KG', 'KG'), ('PCS', 'PCS'), ('PACKET', 'PACKET'), ('LITTER', 'LITTER')], default='PCS', max_length=15),
        ),
    ]
