# Generated by Django 4.2 on 2024-06-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_product_is_active_product_bar_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='bar_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
