# Generated by Django 4.2 on 2024-06-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_alter_product_bar_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qr_image',
        ),
    ]
