# Generated by Django 4.2 on 2024-06-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_remove_product_qr_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.IntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('order_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.orderproduct')),
            ],
        ),
    ]
