# Generated by Django 4.2 on 2024-06-29 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_returnproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='returnproduct',
            name='is_damage',
            field=models.BooleanField(default=False),
        ),
    ]
