# Generated by Django 4.2 on 2024-06-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_returnproduct_is_damage'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
