# Generated by Django 4.2 on 2024-07-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_order_name_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='cart',
            name='vat',
            field=models.FloatField(default=15.0),
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='order',
            name='vat',
            field=models.FloatField(default=15.0),
        ),
    ]
