# Generated by Django 4.2 on 2024-07-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0032_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='serial_key',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
