# Generated by Django 4.2 on 2024-07-12 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0041_damageproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='damageproduct',
            old_name='Product',
            new_name='damage_product',
        ),
    ]
