# Generated by Django 4.2 on 2024-03-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_category_supplier_and_more'),
        ('transaction', '0002_remove_deposite_date_remove_exprensive_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exprensive',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier'),
        ),
    ]
