# Generated by Django 4.2 on 2024-07-03 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_shopowner'),
        ('transaction', '0004_balance_expense_payment_transaction_delete_deposite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shopowner'),
        ),
    ]
