# Generated by Django 4.2 on 2024-03-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_deposite_date_remove_exprensive_date_and_more'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='supplyer',
        ),
        migrations.DeleteModel(
            name='Supplyer',
        ),
    ]
