# Generated by Django 4.2 on 2024-03-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_inventory_supplyer_delete_supplyer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='name',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='inventory',
            old_name='price',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='inventroy_add_date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='qty',
        ),
        migrations.AddField(
            model_name='inventory',
            name='timestamps',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
