# Generated by Django 4.2 on 2024-03-20 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_supplier_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_id',
            field=models.CharField(max_length=200),
        ),
    ]
