# Generated by Django 4.2 on 2024-03-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_total_alter_supplier_tax_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='product_name',
            new_name='product',
        ),
    ]
