# Generated by Django 4.2 on 2024-03-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_user'),
        ('inventory', '0007_rename_product_name_inventory_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
