# Generated by Django 4.2 on 2024-03-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_product_user'),
        ('inventory', '0008_inventory_subtotal_remove_inventory_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AddField(
            model_name='inventory',
            name='products',
            field=models.ManyToManyField(related_name='inventories', to='product.product'),
        ),
    ]
