# Generated by Django 4.2 on 2024-03-21 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_remove_inventory_product_inventory_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='products',
            new_name='product',
        ),
    ]
