# Generated by Django 4.2 on 2024-06-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_remove_inventory_product_remove_inventory_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='timestamps',
        ),
        migrations.AddField(
            model_name='inventory',
            name='added_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
