# Generated by Django 4.2 on 2024-06-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_remove_inventory_timestamps_inventory_added_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='added_date',
            new_name='date',
        ),
    ]
