# Generated by Django 4.2 on 2024-06-29 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_orderproduct_is_returned'),
        ('inventory', '0013_rename_added_date_inventory_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnToSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_quantity', models.IntegerField()),
                ('return_reason', models.TextField(blank=True)),
                ('return_date', models.DateField(auto_now_add=True)),
                ('is_damage', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier')),
            ],
        ),
    ]
