# Generated by Django 4.2 on 2024-06-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_returntosupplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
