# Generated by Django 4.2 on 2024-06-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_supplier_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='amount',
            new_name='unpaid_amount',
        ),
    ]
