# Generated by Django 4.2 on 2024-06-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_rename_amount_supplier_unpaid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
