# Generated by Django 4.2 on 2024-03-19 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_payment_type_checkout_payment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pos',
            name='product',
        ),
    ]
